#!perl
use strict;
use warnings;
use utf8;
use Dist::Template;
Dist::Template->new->create(@ARGV);

__END__

=head1 SYNOPSIS

    $ distt Hello::World
    $ cd Hello-World
    $ ls -F
    Changes  Daikufile  Makefile.PL  cpanfile  lib/  t/

    $ daiku --tasks
    daiku all    # (this is default) test, regen
    daiku test   # run test cases
    daiku clean  # cleanup
    daiku regen  # regenerate README.md and META.json

    $ daiku

=cut
